### ISSUE TITLE
Double jsonencoded

### ISSUE THREAD

**Issue by bobbydeveaux** [humanitec-architecture/example-library#55]
https://github.com/humanitec-architecture/example-library/blob/2da269e0f98dd44f361294b1dfa7e5f27df11858/resource-definitions/ingress/ingress/ingress-alb.tf#L15

This should not have the 2nd Jsonencode

**Comment by TobiasBabin** [comment]
That's right, well spotted! Working on a fix,

**Comment by TobiasBabin** [comment]
@bobbydeveaux  Please see this PR: https://github.com/humanitec-architecture/example-library/pull/65

**Comment by TobiasBabin** [comment]
Closing with https://github.com/humanitec-architecture/example-library/pull/65 merged.
